### ISSUE TITLE
Invalid Split antecedent annotation

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/UD_English-GUM#11]
According to the [README](https://github.com/UniversalDependencies/UD_English-GUM/blob/1933bb/README.md#additional-annotations-in-misc) and [UA docs](https://github.com/UniversalAnaphora/UniversalAnaphora/blob/main/UA_CONLL_U_proposal_amir.md#split-antecedent), Split antecedent should have form
`Split=person-1<person-3,person-2<person-3`
and I deduce that such annotation can appear only on a line containing `Entity=(person-3`.

However, there are three cases in `GUM_bio_holt` where this rule is broken:
* [Entity=(time-123(time-124)|Split=time-12<time-123,time-12<time-124](https://github.com/UniversalDependencies/UD_English-GUM/blob/1933bb18/not-to-release/sources/GUM_bio_holt.conllu#L753)
* [Entity=(time-160(time-161)|Split=time-26<time-160,time-26<time-161](https://github.com/UniversalDependencies/UD_English-GUM/blob/1933bb18/not-to-release/sources/GUM_bio_holt.conllu#L998)
* [Entity=(time-173(time-174)|Split=time-172<time-173,time-172<time-174](https://github.com/UniversalDependencies/UD_English-GUM/blob/1933bb18/not-to-release/sources/GUM_bio_holt.conllu#L1076)

In the first case: `time-123`="September 1", `time-124`="September", `time-12`="2012". The other two cases are similar.
I think this is not a split antecedent case.
I also think this should not be coreference (September vs 2012), as suggested by the [original annotation](https://github.com/amir-zeldes/gum/blob/2a08bccfc63f5d2741e4fce6e04b200ab5a2f5fd/coref/tsv/GUM_bio_holt.tsv#L667) (although I admit I don't understand the tsv format yet), but bridging.

**Comment by amir-zeldes** [comment]
Hmm that's weird, thanks for spotting it! It is indeed supposed to be bridging (September of: -> 2012), and in fact it is annotated that way in the original file. The place to look at in the tsv is the target of the edge, not the source, so you can see the intended bridging edge here, on "2012":

https://github.com/amir-zeldes/gum/blob/2a08bccfc63f5d2741e4fce6e04b200ab5a2f5fd/coref/tsv/GUM_bio_holt.tsv#L638

This must be an error in the UD converter. I'll have to debug and fix this. Is it really only happening in GUM_bio_holt? I wonder what's special about it...

**Comment by martinpopel** [comment]
> Is it really only happening in GUM_bio_holt?

Yes. I processed whole dev, test and train files in the UD dev branch and the only three occurrences of this problem were in the GUM_bio_holt document.

I have a weakly related question about Bridging. The original data contain also the type of bridging relation, but the current UD conversion does not. Am I right?

**Comment by amir-zeldes** [comment]
Fixed in dev
