### ISSUE TITLE
Commas used both as separators in Bridge and within Wikification

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/UD_English-GUM#12]
Comma is used to separate bridging links in `Bridge`, e.g.
* [Bridge=time-12<time-123,time-12<time-124|Entity=(time-123(time-124)](https://github.com/UniversalDependencies/UD_English-GUM/blob/e4bbaeca/not-to-release/sources/GUM_bio_holt.conllu#L753)

However, commas can be also part of Entity IDs when wikification is included. Parsing `Bridge` is thus ambiguous, e.g.:
* [Bridge=place-1-Fort_Lee,_New_Jersey<place-118](https://github.com/UniversalDependencies/UD_English-GUM/blob/e4bbaec/not-to-release/sources/GUM_voyage_fortlee.conllu#L842)

My suggestion is to escape all commas in Entity IDs with `%2C` (the [URL](https://en.wikipedia.org/wiki/Fort_Lee%2C_New_Jersey) will be still valid).

**Comment by amir-zeldes** [comment]
Ooh, nice catch! Yes, we are already using URL encoding for parentheses, just forgot about this one. Will fix.

**Comment by amir-zeldes** [comment]
Resolved in 6c0cd45 and  UniversalDependencies/UD_English-GUMReddit@ef6a885
