### ISSUE TITLE
Single sentence split into two

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-GUM#14]
`# sent_id = GUM_academic_thrones-9`
`# sent_id = GUM_academic_thrones-10`

`Transmedia systems, like that exemplified by Game of Thrones, are becoming increasingly prevalent (e.g., Star Wars, Harry Potter, The Walking Dead, the Marvel Cinematic Universe, etc);`

and

`these systems demonstrate, in microcosm, the global challenge of managing the fire-hose flow of information in contemporary postdigital society.`

**Comment by amir-zeldes** [comment]
Thanks for catching, will fix
