### ISSUE TITLE
libertarian

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-GUM#15]
2 tokens of libertarian/PROPN that should be capitalized in the lemma.

**Comment by amir-zeldes** [comment]
I think for the following that's right:

  * he would be a Libertarian today (should be NNP/Libertarian)

But I'm a little unsure what to do about this one:

  * a self-described Libertarian Socialist

My problem is this:

  * Demonym-like capitalized adjectives are normatively tagged as NNP in PTB if they are substitutive (stand for people), but not as modifiers of common nouns: "an American/NNP" but "an American/JJ hamburger". For American/JJ it makes sense that the lemma is "American"
  * For "Libertarian Socialist", my sense is that socialist is actually a common noun, and not a demonym. So it should be Socialist/NN/socialist, right?
  * But then Libertarian is a modifier JJ of a common noun, so it is Libertarian/JJ. Are we still saying it should have a capitalized lemma, even though it is not a demonym and not NNP? Or should it be NNP (and also amod?)? Is there a lower-cased version of libertarian similar to socialist?

**Comment by nschneid** [comment]
Yes, there is the libertarian philosophy as well as the Libertarian Party. Perhaps the author was overcapitalizing in the second example.

**Comment by amir-zeldes** [comment]
Went with "a Libertarian/JJ/Libertarian Socialist/NN/socialist"
