### ISSUE TITLE
Suddenly I can't read the 'upos' from en_gum-ud-test.conllu

### ISSUE THREAD

**Issue by DanielShterenberg** [UniversalDependencies/UD_English-GUM#16]
I used to extract the data and tags using:
```
for sentence in data: 
  for word in sentence: 
    w = word['form']
    t = word['upos']
 ```

Suddenly, I can't extract the upos. I think that the error is in the sentence "Importantly, studying eye movements offers an insight that does not depend on the participants’ beliefs, memories or subjective impressions of the artwork.", and specifically in the word "participants’" (mind the `).

How can it be fixed?

Thanks ahead.

**Comment by amir-zeldes** [comment]
Hi - you didn't specify what Python library you're using to read the data, so it's hard to be sure, but given the word you pointed out, I'm guessing you have a script that can't handle the new multiword tokens (MWTs) which were added in the most recent UD version 2.8. 

Specifically, this release includes MWT token IDs with hyphens in the ID number which cover multiple regular tokens spelled together, in this case:

```CoNLL-U
14	the	the	DET	DT	Definite=Def|PronType=Art	15	det	15:det	Entity=(abstract-103
15-16	participants’	_	_	_	_	_	_	_	_
15	participants	participant	NOUN	NNS	Number=Plur	17	nmod:poss	17:nmod:poss	Entity=(person-104
16	’	's	PART	POS	_	15	case	15:case	Entity=person-104)
17	beliefs	belief	NOUN	NNS	Number=Plur	12	obl	12:obl:on	Entity=abstract-103)|SpaceAfter=No
```

Where `15-16` is a MWT. As you can see, the columns that normally contain POS tags are blank for such tokens, which can look like some token has no POS tag (but in fact, these are not really regular tokens at all). For more information, please see the CoNLL-U documentation here:

https://universaldependencies.org/format.html

**Comment by DanielShterenberg** [comment]
Thanks for the explanation @amir-zeldes. I'm using `conllutils` and iterate over all the words and extract them as mentioned above. 
I will find another way. Sorry for the confusion.

**Comment by amir-zeldes** [comment]
I see, I think the `conllu` library supports MWTs, and `updapi` should as well, so those might be worth checking out.

**Comment by martinpopel** [comment]
Yes, [Udapi](https://github.com/udapi/udapi-python) can handle MWTs:
```python
import udapi
doc = udapi.Document("en_gum-ud-train.conllu", sent_id_filter="GUM_academic_art-22")
doc.draw()
for tree in doc.trees:
    for word in tree.descendants:
        print(word.form, word.upos)
for tree in doc.trees:
    for mwt in tree.multiword_tokens;
        print(mwt.form)
        for word in mwt.words:
            print(word.form, word.upos)
```
