### ISSUE TITLE
A few errors with 'mark' going in the wrong direction

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-GUM#2]
[Query](http://bionlp-www.utu.fi/dep_search/query?search=_%20%3Emark%40R%20_&db=UD_English-GUM-dev&case_sensitive=True&hits_per_page=10)

For the one where "the" and "to" are swapped, I would just list them as typos (Typo=Yes) rather than treating it as weird word order.

**Comment by amir-zeldes** [comment]
2 and 5 are definitely just plain errors. 3 and 4 are promotion errors, i.e. infinitives missing their verb, so 'to' should be promoted to `xcomp` here (so also an error, but not just arbitrary; I'm not sure I want to read that 'to' as 'the', that's maybe subjective?). I think 1 is actually correct - that 'to' is a `mark` to the fronted predicate 'being what', so based on the copula analysis with 'what' as the predicate, the `mark` pointing to the right is correct, no? I think it would be the same for any "what to be" situation.

I can fix the four errors, but I assume @dan-zeman would like this to wait until after the release? If not, we can also get them done by tomorrow, just let me know.

**Comment by amir-zeldes** [comment]
OK corrections are done and will be pushed once data freeze is lifted

**Comment by dan-zeman** [comment]
@amir-zeldes : You can push now. The release is not yet officially out but I'm done with the treebank repos.
