### ISSUE TITLE
Tagging errors for "in"

### ISSUE THREAD

**Issue by muchang** [UniversalDependencies/UD_English-GUM#22]
According to [Universal Dependencies](https://universaldependencies.org/u/pos/ADP.html), when "in" acts as a verbal particle, it should be tagged `ADP`. 
> Note that in Germanic languages, some prepositions may also function as verbal particles, as in give in or hold on. They are still tagged ADP and not PART.

In GUM, some (about 10) "in"s that act as verbal particles are tagged as `ADV`. For example:
```
# sent_id = GUM_fiction_frankenstein-84
# s_type = decl
# text = She opens the garage door so I can get in.
1	She	she	PRON	PRP	Case=Nom|Gender=Fem|Number=Sing|Person=3|PronType=Prs	2	nsubj	2:nsubj	Discourse=sequence:178->9|Entity=(person-5)
2	opens	open	VERB	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	0	root	0:root	_
3	the	the	DET	DT	Definite=Def|PronType=Art	5	det	5:det	Bridge=place-69<object-88|Entity=(object-88
4	garage	garage	NOUN	NN	Number=Sing	5	compound	5:compound	Entity=(place-89)
5	door	door	NOUN	NN	Number=Sing	2	obj	2:obj	Entity=object-88)
6	so	so	SCONJ	IN	_	9	mark	9:mark	Discourse=purpose:179->178
7	I	I	PRON	PRP	Case=Nom|Number=Sing|Person=1|PronType=Prs	9	nsubj	9:nsubj	Entity=(person-6)
8	can	can	AUX	MD	VerbForm=Fin	9	aux	9:aux	_
9	get	get	VERB	VB	VerbForm=Inf	2	advcl	2:advcl:so	_
10	in	in	ADV	RB	Degree=Pos	9	advmod	9:advmod	SpaceAfter=No
11	.	.	PUNCT	.	_	2	punct	2:punct	_
```
```
# sent_id = GUM_fiction_rose-35
# s_type = decl
# text = Sunlight streaming in through a high window opposite her lit up the fine hairs on her arm, the embroidered flowers on the collar of her white shirt.
1	Sunlight	sunlight	NOUN	NN	Number=Sing	10	nsubj	10:nsubj	Discourse=joint:82->79|Entity=(substance-71
2	streaming	stream	VERB	VBG	VerbForm=Ger	1	acl	1:acl	Discourse=antithesis:83->82
3	in	in	ADV	RB	Degree=Pos	2	advmod	2:advmod	_
4	through	through	ADP	IN	_	7	case	7:case	_
5	a	a	DET	DT	Definite=Ind|PronType=Art	7	det	7:det	Entity=(object-72
6	high	high	ADJ	JJ	Degree=Pos	7	amod	7:amod	_
7	window	window	NOUN	NN	Number=Sing	2	obl	2:obl:through	_
8	opposite	opposite	ADP	IN	_	9	case	9:case	_
9	her	she	PRON	PRP	Case=Acc|Gender=Fem|Number=Sing|Person=3|PronType=Prs	7	nmod	7:nmod:opposite	Entity=(person-5)substance-71)object-72)
10	lit	light	VERB	VBD	Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin	0	root	0:root	Discourse=same-unit:84->82
11	up	up	ADP	RP	_	10	compound:prt	10:compound:prt	_
12	the	the	DET	DT	Definite=Def|PronType=Art	14	det	14:det	Entity=(object-73
13	fine	fine	ADJ	JJ	Degree=Pos	14	amod	14:amod	_
14	hairs	hair	NOUN	NNS	Number=Plur	10	obj	10:obj	_
15	on	on	ADP	IN	_	17	case	17:case	_
16	her	her	PRON	PRP$	Gender=Fem|Number=Sing|Person=3|Poss=Yes|PronType=Prs	17	nmod:poss	17:nmod:poss	Entity=(object-74(person-5)
17	arm	arm	NOUN	NN	Number=Sing	14	nmod	14:nmod:on	Entity=object-73)object-74)|SpaceAfter=No
18	,	,	PUNCT	,	_	21	punct	21:punct	_
19	the	the	DET	DT	Definite=Def|PronType=Art	20	det	20:det	Entity=(object-75
20	embroidered	embroider	VERB	VBN	Tense=Past|VerbForm=Part	21	amod	21:amod	_
21	flowers	flower	NOUN	NNS	Number=Plur	14	conj	10:obj|14:conj	_
22	on	on	ADP	IN	_	24	case	24:case	_
23	the	the	DET	DT	Definite=Def|PronType=Art	24	det	24:det	Entity=(object-76
24	collar	collar	NOUN	NN	Number=Sing	21	nmod	21:nmod:on	_
25	of	of	ADP	IN	_	28	case	28:case	_
26	her	her	PRON	PRP$	Gender=Fem|Number=Sing|Person=3|Poss=Yes|PronType=Prs	28	nmod:poss	28:nmod:poss	Entity=(object-77(person-5)
27	white	white	ADJ	JJ	Degree=Pos	28	amod	28:amod	_
28	shirt	shirt	NOUN	NN	Number=Sing	24	nmod	24:nmod:of	Entity=object-75)object-76)object-77)|SpaceAfter=No
29	.	.	PUNCT	.	_	10	punct	10:punct	_
```
```
# sent_id = GUM_voyage_chatham-13
# s_type = imp
# text = Get in
1	Get	get	VERB	VB	Mood=Imp|Person=2|VerbForm=Fin	0	root	0:root	Discourse=preparation:24->26
2	in	in	ADV	RB	Degree=Pos	1	advmod	1:advmod	_
``` 

Commit: d38df82

**Comment by nschneid** [comment]
I take it "verbal particle" means it is ADP when it attaches as `compound:prt`, and when it attaches as `advmod` it should be ADV. So the above tags are consistent with the deprels. Whether the `advmod` vs. `compound:prt` distinction is actually implemented consistently is another story....

**Comment by muchang** [comment]
Thanks, Nathan. If it is possible that the deprels are also not correct? What makes me puzzled is that "hold on" and "get in" seem not very different.

**Comment by amir-zeldes** [comment]
Thanks for raising this issue and for the examples - the intended behavior in GUM, which I think is mostly consistent, is indeed "get in/RB/advmod", and it is modeled directly on the behavior of xpos in PTB. PTB examples:

  * customers now can get in/RB only through a buzzer (wsj_0730)
  * once you get in/RB , you ca n't get out /RB (wsj_1492)

There are no PTB instances with RP for this combination. In terms of the PTB guidelines and understanding why this is so, I think the relevant part about the distinction between RP and RB is Santorini (1990:21) is:

> "the idiomaticity of a particular collocation is not a diagnostic for the distinction"

And:

> "A word is an adverb (RB) rather than a particle (RP) if you can insert a manner adverb between the verb
and the word"

So presumably PTB annotators felt comfortable with things like "get directly in". I must confess that if it were not for the PTB precedents, which GUM annotators regularly check for, I would have also expected RP here, and a previous round of revisions actually targeted such cases explicitly (i.e. made them RB for combinations that are RB in PTB). Of course it is very possible some cases have been missed or revised backwards in the meantime...

**Comment by muchang** [comment]
Thanks for your detailed explanation, Amir. "A word is an adverb (RB) rather than a particle (RP) if you can insert a manner adverb between the verb and the word" sounds like a golden rule to distinct RB and RP.  I am convinced by the term "get directly in" to consider the "in" in "get in" as RB. 

> I must confess that if it were not for the PTB precedents, which GUM annotators regularly check for, I would have also expected RP here, and a previous round of revisions actually targeted such cases explicitly (i.e. made them RB for combinations that are RB in PTB).

Yes, being consistent with PTB would be a practical choice, especially since some tools are trained across different corpora. Also thanks for the awesome work of the GUM annotators to continually revise GUM. 

> Of course it is very possible some cases have been missed or revised backwards in the meantime...

If I find any such cases, I will report them here.
