### ISSUE TITLE
Tagging errors for ADP/ADV

### ISSUE THREAD

**Issue by muchang** [UniversalDependencies/UD_English-GUM#23]
Similar to #22, according to [Universal Dependencies](https://universaldependencies.org/u/pos/ADV.html), when "down" acts as a verbal particle, it should be tagged `ADV`.
> Note that in Germanic languages, some adverbs may also function as verbal particles, as in write down or end up. They are still tagged ADV and not PART.

In GUM, around 50 "down"s are tagged `ADP` when they act as verbal particles. For example:
```
# sent_id = GUM_fiction_frankenstein-51
# s_type = decl
# text = She tries to sit down, but I just keep on tugging and she follows me, gulping and wailing.
1	She	she	PRON	PRP	Case=Nom|Gender=Fem|Number=Sing|Person=3|PronType=Prs	2	nsubj	2:nsubj|4:nsubj:xsubj	Discourse=sequence:105->102|Entity=(person-2)
2	tries	try	VERB	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	0	root	0:root	_
3	to	to	PART	TO	_	4	mark	4:mark	_
4	sit	sit	VERB	VB	VerbForm=Inf	2	xcomp	2:xcomp	_
5	down	down	ADP	RP	_	4	compound:prt	4:compound:prt	SpaceAfter=No
6	,	,	PUNCT	,	_	10	punct	10:punct	_
7	but	but	CCONJ	CC	_	10	cc	10:cc	Discourse=contrast:106->105
8	I	I	PRON	PRP	Case=Nom|Number=Sing|Person=1|PronType=Prs	10	nsubj	10:nsubj|12:nsubj:xsubj	Entity=(person-6)
9	just	just	ADV	RB	_	10	advmod	10:advmod	_
10	keep	keep	VERB	VBP	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	2	conj	2:conj:but	_
11	on	on	ADP	RP	_	10	compound:prt	10:compound:prt	_
12	tugging	tug	VERB	VBG	VerbForm=Ger	10	xcomp	10:xcomp	_
13	and	and	CCONJ	CC	_	15	cc	15:cc	Discourse=result:107->106
14	she	she	PRON	PRP	Case=Nom|Gender=Fem|Number=Sing|Person=3|PronType=Prs	15	nsubj	15:nsubj	Entity=(person-2)
15	follows	follow	VERB	VBZ	Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin	10	conj	2:conj|10:conj:and	_
16	me	I	PRON	PRP	Case=Acc|Number=Sing|Person=1|PronType=Prs	15	obj	15:obj	Entity=(person-6)|SpaceAfter=No
17	,	,	PUNCT	,	_	18	punct	18:punct	_
18	gulping	gulp	VERB	VBG	VerbForm=Ger	15	advcl	15:advcl	Discourse=manner:108->107
19	and	and	CCONJ	CC	_	20	cc	20:cc	Discourse=joint:109->108
20	wailing	wail	VERB	VBG	VerbForm=Ger	18	conj	15:advcl|18:conj:and	SpaceAfter=No
21	.	.	PUNCT	.	_	2	punct	2:punct	_
```
```
# sent_id = GUM_fiction_pixies-8
# s_type = decl
# text = I threw down my pen and dashed down the hall.
1	I	I	PRON	PRP	Case=Nom|Number=Sing|Person=1|PronType=Prs	2	nsubj	2:nsubj|7:nsubj	Discourse=result:11->7|Entity=(person-7)
2	threw	throw	VERB	VBD	Mood=Ind|Number=Sing|Person=1|Tense=Past|VerbForm=Fin	0	root	0:root	_
3	down	down	ADP	RP	_	2	compound:prt	2:compound:prt	_
4	my	my	PRON	PRP$	Number=Sing|Person=1|Poss=Yes|PronType=Prs	5	nmod:poss	5:nmod:poss	Entity=(object-20(person-7)
5	pen	pen	NOUN	NN	Number=Sing	2	obj	2:obj	Entity=object-20)
6	and	and	CCONJ	CC	_	7	cc	7:cc	Discourse=sequence:12->11
7	dashed	dash	VERB	VBD	Mood=Ind|Number=Sing|Person=1|Tense=Past|VerbForm=Fin	2	conj	2:conj:and	_
8	down	down	ADP	IN	_	10	case	10:case	_
9	the	the	DET	DT	Definite=Def|PronType=Art	10	det	10:det	Entity=(place-21
10	hall	hall	NOUN	NN	Number=Sing	7	obl	7:obl:down	Entity=place-21)|SpaceAfter=No
11	.	.	PUNCT	.	_	2	punct	2:punct	_
```
```
# sent_id = GUM_fiction_honour-16
# s_type = decl
# text = The enormous forms of the battleships loomed like giants atop a hill, staring down upon a tiny village below.
1	The	the	DET	DT	Definite=Def|PronType=Art	3	det	3:det	Discourse=elaboration:28->18|Entity=(object-45
2	enormous	enormous	ADJ	JJ	Degree=Pos	3	amod	3:amod	_
3	forms	form	NOUN	NNS	Number=Plur	7	nsubj	7:nsubj	_
4	of	of	ADP	IN	_	6	case	6:case	_
5	the	the	DET	DT	Definite=Def|PronType=Art	6	det	6:det	Entity=(object-46
6	battleships	battleship	NOUN	NNS	Number=Plur	3	nmod	3:nmod:of	Entity=object-45)object-46)
7	loomed	loom	VERB	VBD	Mood=Ind|Number=Plur|Person=3|Tense=Past|VerbForm=Fin	0	root	0:root	_
8	like	like	ADP	IN	_	9	case	9:case	_
9	giants	giant	NOUN	NNS	Number=Plur	7	obl	7:obl:like	Entity=(person-47
10	atop	atop	ADP	IN	_	12	case	12:case	_
11	a	a	DET	DT	Definite=Ind|PronType=Art	12	det	12:det	Entity=(place-48
12	hill	hill	NOUN	NN	Number=Sing	9	nmod	9:nmod:atop	Entity=person-47)place-48)|SpaceAfter=No
13	,	,	PUNCT	,	_	14	punct	14:punct	_
14	staring	stare	VERB	VBG	VerbForm=Ger	7	advcl	7:advcl	Discourse=elaboration:29->28
15	down	down	ADP	RP	_	14	compound:prt	14:compound:prt	_
16	upon	upon	ADP	IN	_	19	case	19:case	_
17	a	a	DET	DT	Definite=Ind|PronType=Art	19	det	19:det	Entity=(place-49
18	tiny	tiny	ADJ	JJ	Degree=Pos	19	amod	19:amod	_
19	village	village	NOUN	NN	Number=Sing	14	obl	14:obl:upon	Entity=place-49)
20	below	below	ADV	RB	Degree=Pos	19	advmod	19:advmod	SpaceAfter=No
21	.	.	PUNCT	.	_	7	punct	7:punct	_
```

Commit: d38df82

**Comment by nschneid** [comment]
It is not clear why verb particles "down" and "up" are specified as ADV in the guidelines while verb particles "in" and "on" [are specified as ADP](https://universaldependencies.org/u/pos/ADP.html). See UniversalDependencies/UD_English-EWT#135, UniversalDependencies/docs#771. For now, EWT and GUM tag them all as ADP.

**Comment by muchang** [comment]
Thanks, Nathan. It seems the question is still unclear according to your discussions. 

I am not able to help on the linguistic perspective, but I notice some inconsistencies in GUM.

For example,
```
# sent_id = GUM_fiction_garden-32
# s_type = decl
# text = We clambered up onto the roof, sliding on the tiles and clinging to chimney stacks, sheltering our eyes from the driving downpour.
1	We	we	PRON	PRP	Case=Nom|Number=Plur|Person=1|PronType=Prs	2	nsubj	2:nsubj	Discourse=sequence:106->93|Entity=(person-38)
2	clambered	clamber	VERB	VBD	Mood=Ind|Number=Plur|Person=1|Tense=Past|VerbForm=Fin	0	root	0:root	_
3	up	up	ADV	RB	Degree=Pos	2	advmod	2:advmod	_
4	onto	onto	ADP	IN	_	6	case	6:case	_
5	the	the	DET	DT	Definite=Def|PronType=Art	6	det	6:det	Entity=(place-43
6	roof	roof	NOUN	NN	Number=Sing	2	obl	2:obl:onto	Entity=place-43)|SpaceAfter=No
7	,	,	PUNCT	,	_	8	punct	8:punct	_
8	sliding	slide	VERB	VBG	VerbForm=Ger	2	advcl	2:advcl	Discourse=manner:107->106
9	on	on	ADP	IN	_	11	case	11:case	_
10	the	the	DET	DT	Definite=Def|PronType=Art	11	det	11:det	Entity=(object-125
11	tiles	tile	NOUN	NNS	Number=Plur	8	obl	8:obl:on	Entity=object-125)
12	and	and	CCONJ	CC	_	13	cc	13:cc	Discourse=joint:108->107
13	clinging	cling	VERB	VBG	VerbForm=Ger	8	conj	2:advcl|8:conj:and	_
14	to	to	ADP	IN	_	16	case	16:case	_
15	chimney	chimney	NOUN	NN	Number=Sing	16	compound	16:compound	Entity=(object-126
16	stacks	stack	NOUN	NNS	Number=Plur	13	obl	13:obl:to	Entity=object-126)|SpaceAfter=No
17	,	,	PUNCT	,	_	18	punct	18:punct	_
18	sheltering	shelter	VERB	VBG	VerbForm=Ger	2	advcl	2:advcl	Discourse=joint:109->107
19	our	our	PRON	PRP$	Number=Plur|Person=1|Poss=Yes|PronType=Prs	20	nmod:poss	20:nmod:poss	Entity=(object-127(person-38)
20	eyes	eye	NOUN	NNS	Number=Plur	18	obj	18:obj	Entity=object-127)
21	from	from	ADP	IN	_	24	case	24:case	_
22	the	the	DET	DT	Definite=Def|PronType=Art	24	det	24:det	Entity=(substance-16
23	driving	driving	ADJ	JJ	Degree=Pos	24	amod	24:amod	_
24	downpour	downpour	NOUN	NN	Number=Sing	18	obl	18:obl:from	Entity=substance-16)|SpaceAfter=No
25	.	.	PUNCT	.	_	2	punct	2:punct	_
```
In this sentence, "up" is tagged as `ADV` while it is a verb particle. It seems this "up" should have the same POS tag as "down" in "sent_id = GUM_fiction_frankenstein-51" above.

**Comment by amir-zeldes** [comment]
See my comment [here](https://github.com/UniversalDependencies/UD_English-GUM/issues/22#issuecomment-874050719)

Basically for purely directional cases, PTB uses xpos=RB and not RP, including for "up":

  * when market interest rates move up/RB rapidly (wsj_0238)
  * the Olympics may help CBS move up/RB to No. 2 (wsj_1057)

So it is not considered a particle here, and note the deprel is also `advmod`. In fact, the GUM build bot should throw a warning if a token with deprel `advmod` were tagged `RP` (or `compound:prt` with `RB`), so it is unlikely that there are mismatches in the current release.

> It is not clear why verb particles "down" and "up" are specified as ADV in the guidelines

Yes, if they are particles I agree they should be RP/ADP/compound:prt (e.g. pick up/RP/ADP), but there are also ADV cases in GUM, in which case they are RB/ADV/advmod.

**Comment by muchang** [comment]
Thanks, Amir. If I interpret your comments correctly, the "down"s here should be all tagged as RB rather than RP, right? Because they are all purely directional cases that are tagged as RB in PTB.

**Comment by amir-zeldes** [comment]
Actually, things are little more complicated for a number of reasons... First, for transitive verbs PTB uses the movability around objects as a criterion for identifying RP, which matches the case of "threw down my pen" (compare: "threw my pen down"). As a result, this particular combination has been tagged as RP in the past (only appearing once in PTB, but 8 times in OntoNotes, which is a superset of PTB).

For "sit down" things are a little more ambiguous IMO, since its intransitive, but not 100% clearly directional - I agree that the literal sense seems directional, but hypothetically you could be lying and then sitting down, without standing up first. I'd honestly be OK with "sit down/RB" based on a spatial reading, but PTB is split on this (twice RB, four times RP), while the added data in OntoNotes seems to also overwhelmingly prefer RP (30xRP, 6xRB). Based on this precedent and the murky directionality (maybe it's just lexicalized to mean "sit"), I would leave it as RP.

But, for "look down" meaning "look downward" (not "disdain, scoff at"), I agree it should be RB and OntoNotes agrees - it's 12xRB vs. 4xRP, and all of the RP cases mean "disdain". I'll make sure to fix the instance in GUM_fiction_honour-16 to match this. Thanks again for noticing this!

**Comment by nschneid** [comment]
If you're statively sitting down (seated rather than standing), it is sort of directional because you are below some higher vantage point. This could be called fictive motion. Similarly, stocks are down (from where they were yesterday).

(Note that this is one advantage of the CGEL approach combining particles and prepositions—less gray area! But I realize that doesn't help us for PTB/UD.)

**Comment by nschneid** [comment]
Anyway, by the manner adverb test, the concrete dynamic readings are RB: sit slowly down, look shyly down

**Comment by amir-zeldes** [comment]
Well, as I wrote above, I would have probably been OK with RB for sit down, but the PTB precedent gives me pause, since we do a lot of things with either concatenating or ensembling over PTB/OntoNotes and GUM, so if I don't have a strong reasons to diverge from them I'd rather not. More specifically for this sentence, I don't think those adverbs would work here:

  * She tries to sit (??slowly) down, but I just keep on tugging

I would have definitely said "sit down slowly" here. So it's possible the adverbs distinguish those cases where the motion is being emphasized in a particularly transparent way, and maybe there are instances that should be tagged RB, but here RP seems like the better choice overall.

**Comment by muchang** [comment]
In the following sentences, the words seem to be RB since it is possible to insert a manner adverb.

Word: "down"
```
# sent_id = GUM_whow_chicken-6
# s_type = imp
# text = Hold the chicken down on a flat surface.
1	Hold	hold	VERB	VB	Mood=Imp|Person=2|VerbForm=Fin	0	root	0:root	Discourse=ROOT:15
2	the	the	DET	DT	Definite=Def|PronType=Art	3	det	3:det	Entity=(animal-17
3	chicken	chicken	NOUN	NN	Number=Sing	1	obj	1:obj	Entity=animal-17)
4	down	down	ADP	RP	_	1	compound:prt	1:compound:prt	_
5	on	on	ADP	IN	_	8	case	8:case	_
6	a	a	DET	DT	Definite=Ind|PronType=Art	8	det	8:det	Entity=(place-18
7	flat	flat	ADJ	JJ	Degree=Pos	8	amod	8:amod	_
8	surface	surface	NOUN	NN	Number=Sing	1	obl	1:obl:on	Entity=place-18)|SpaceAfter=No
9	.	.	PUNCT	.	_	1	punct	1:punct	_
```

Word: "around"
```
# sent_id = GUM_whow_quidditch-29
# s_type = decl
# text = The snitch, generally a track runner, runs around (usually the boundaries) trying to evade the seekers.
1	The	the	DET	DT	Definite=Def|PronType=Art	2	det	2:det	Discourse=joint:70->33|Entity=(person-56
2	snitch	snitch	NOUN	NN	Number=Sing	9	nsubj	9:nsubj	Entity=person-56)|SpaceAfter=No
3	,	,	PUNCT	,	_	7	punct	7:punct	_
4	generally	generally	ADV	RB	Degree=Pos	7	advmod	7:advmod	_
5	a	a	DET	DT	Definite=Ind|PronType=Art	7	det	7:det	Entity=(person-56
6	track	track	NOUN	NN	Number=Sing	7	compound	7:compound	_
7	runner	runner	NOUN	NN	Number=Sing	2	appos	2:appos	Entity=person-56)|SpaceAfter=No
8	,	,	PUNCT	,	_	2	punct	2:punct	_
9	runs	run	VERB	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	0	root	0:root	_
10	around	around	ADP	IN	_	14	case	14:case	_
11	(	(	PUNCT	-LRB-	_	14	punct	14:punct	Discourse=elaboration:71->70|SpaceAfter=No
12	usually	usually	ADV	RB	Degree=Pos	14	advmod	14:advmod	_
13	the	the	DET	DT	Definite=Def|PronType=Art	14	det	14:det	Entity=(place-64
14	boundaries	boundary	NOUN	NNS	Number=Plur	9	obl	9:obl:around	Entity=place-64)|SpaceAfter=No
15	)	)	PUNCT	-RRB-	_	14	punct	14:punct	_
16	trying	try	VERB	VBG	VerbForm=Ger	9	advcl	9:advcl	Discourse=purpose:72->70
17	to	to	PART	TO	_	18	mark	18:mark	_
18	evade	evade	VERB	VB	VerbForm=Inf	16	xcomp	16:xcomp	_
19	the	the	DET	DT	Definite=Def|PronType=Art	20	det	20:det	Entity=(person-55
20	seekers	seeker	NOUN	NNS	Number=Plur	18	obj	18:obj	Entity=person-55)|SpaceAfter=No
21	.	.	PUNCT	.	_	9	punct	9:punct	_
```

**Comment by amir-zeldes** [comment]
I think the first one is right, since the pronoun movement test wins here ("hold the chicken down" / "hold down the chicken"). It's also 4/4 RP in OntoNotes. The second one I agree should be RB, though OntoNotes is split: it's 2 RB vs. 2 RP!

**Comment by amir-zeldes** [comment]
Oh, hang on, no I take it back - it's not RP vs RB since it's not "run around". It's "run around the boundaries", so around is actually a normal ADP. The parentheses and the placement of "usually" are just a bit weird, but otherwise the argument structure doesn't make sense.

**Comment by muchang** [comment]
The "(usually the boundaries)" in the second sentence sounds like a parenthesis. However, according to Wikipedia (https://en.wikipedia.org/wiki/Parenthesis_(rhetoric)) 
> The parenthesis could be left out and still form grammatically correct text.

which means "the boundaries" could be omitted when we analyze this sentence. If we omit "the boundaries", the "around" sounds like a RB.

**Comment by amir-zeldes** [comment]
Regardless of what Wikipedia says about parentheses in general, the meaning of the part in parentheses in this case only makes sense if "around" is a preposition:

  * runs around (usually the boundaries)

Run around what? Run around the boundaries. If "run around" is a phrase by itself, it's not clear what "usually the boundaries" means (the boundaries are not running around, so they have to be some non-subject dependent of "run", and the only interpretation I can come up with is "run around the boundaries".

**Comment by nschneid** [comment]
I think the speaker is being a bit casual with syntax here, with the parenthetical added as an afterthought in a way that is not perfectly syntactically coherent. But as far as tagging "around", I will point out that this would not be a problem with the view that adpositions can be intransitive.

**Comment by amir-zeldes** [comment]
I don't thing prepositions being intransitive would solve it, since it doesn't explain the argument structure role of "boundaries". Plus if adpositions could be intransitive, they should be called "ad-"... If anything, I would say the closest thing to an intransitive preposition is simply an adverb, and if we have to connect the two things, I would say the prepositions are transitive adverbs (which, at least for the core prepositions in Indo-European languages, is historically the case)

**Comment by nschneid** [comment]
Unfortunately there's no great name for the core ones that distinguishes them from the -ly ones. I think Bolinger used the term "adprep" as a blend between adverb and preposition.
