### ISSUE TITLE
advmod should be amod

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-GUM#3]
http://bionlp-www.utu.fi/dep_search/query?search=spectacular%20%3Cadvmod%20_&db=UD_English-GUM-dev&case_sensitive=False&hits_per_page=100

**Comment by amir-zeldes** [comment]
I agree it should be `amod`, but I think maybe 'less than' should attach to it as `advmod` rather than `case`. What do you think?

**Comment by nschneid** [comment]
I'd be fine with that. It falls under the category of multiword function words that I never know quite what to do with. :)

**Comment by dan-zeman** [comment]
I would vote for advmod(spectacular, less).

**Comment by amir-zeldes** [comment]
OK, fixed in amir-zeldes/gum@89680b66ff47e04186265b8353683c53eef2f975

If you find more punctual errors like this, feel free to fork and PR into the dev branch of amir-zeldes/gum, and it will propagate into UD_English-GUM for the next release.

**Comment by amir-zeldes** [comment]
One more note though: to fix dependencies, edit _build/src/dep, but to fix POS tags or lemmas, edit _build/src/xml. There's a more detailed overview of what can be fixed where here: 

https://corpling.uis.georgetown.edu/gum/build.html
