### ISSUE TITLE
Prepositions not attaching to the first word of a flat name

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-GUM#4]
[Query with 64 hits](http://bionlp-www.utu.fi/dep_search/query?search=%28%21ADP%20%3Cnmod%20_%29%20%21%3Ecase%20_&db=UD_English-GUM-dev&case_sensitive=False&hits_per_page=100)—this looks like a conversion error, no?

**Comment by amir-zeldes** [comment]
Yikes, yes! Should be easy to fix. Will push with the GUM6 data, but I need to clean up the GUM source repo itself first.

**Comment by amir-zeldes** [comment]
Resolved in amir-zeldes/GUM@e81628bf6e34191684db89cb58412bb680a2c0ac will propagate on next UD release
