### ISSUE TITLE
Annotation errors

### ISSUE THREAD

**Issue by James-Decatur** [UniversalDependencies/UD_English-GUM#47]
When working with Joakim Nivre, we discovered annotation errors that led to the creation of non-projective dependencies ('udapi' can help you visualize and confirm).

- Sentences, where the non-projective dependency is a 'conj' and the head, is a 'case'

File: en_gum-ud-dev, Sent #14: GUM_academic_exposure-14
File: en_gum-ud-dev, Sent #19: GUM_academic_exposure-19
File: en_gum-ud-dev, Sent #21: GUM_academic_exposure-21
File: en_gum-ud-dev, Sent #23: GUM_academic_exposure-23
File: en_gum-ud-dev, Sent #23: GUM_academic_exposure-23
File: en_gum-ud-dev, Sent #35: GUM_academic_librarians-11
File: en_gum-ud-dev, Sent #82: GUM_bio_emperor-5
File: en_gum-ud-dev, Sent #98: GUM_bio_emperor-21
File: en_gum-ud-dev, Sent #278: GUM_fiction_beast-3
File: en_gum-ud-dev, Sent #667: GUM_voyage_athens-2
File: en_gum-ud-dev, Sent #717: GUM_voyage_coron-11
File: en_gum-ud-dev, Sent #730: GUM_voyage_coron-24
File: en_gum-ud-test, Sent #18: GUM_academic_discrimination-18
File: en_gum-ud-test, Sent #85: GUM_academic_eegimaa-31
File: en_gum-ud-test, Sent #89: GUM_academic_eegimaa-35
File: en_gum-ud-test, Sent #90: GUM_academic_eegimaa-36
File: en_gum-ud-test, Sent #98: GUM_bio_dvorak-8
File: en_gum-ud-test, Sent #102: GUM_bio_dvorak-12
File: en_gum-ud-test, Sent #102: GUM_bio_dvorak-12
File: en_gum-ud-test, Sent #127: GUM_bio_jespersen-8
File: en_gum-ud-test, Sent #133: GUM_bio_jespersen-14
File: en_gum-ud-test, Sent #133: GUM_bio_jespersen-14
File: en_gum-ud-test, Sent #414: GUM_interview_hill-30
File: en_gum-ud-test, Sent #457: GUM_interview_libertarian-15
File: en_gum-ud-test, Sent #470: GUM_interview_libertarian-28
File: en_gum-ud-test, Sent #528: GUM_news_nasa-44
File: en_gum-ud-test, Sent #719: GUM_voyage_oakland-8
File: en_gum-ud-test, Sent #722: GUM_voyage_oakland-11
File: en_gum-ud-test, Sent #735: GUM_voyage_oakland-24
File: en_gum-ud-test, Sent #840: GUM_whow_mice-11
File: en_gum-ud-test, Sent #856: GUM_whow_mice-27
File: en_gum-ud-test, Sent #861: GUM_whow_mice-32
File: en_gum-ud-train, Sent #14: GUM_academic_art-14
File: en_gum-ud-train, Sent #30: GUM_academic_census-2
File: en_gum-ud-train, Sent #129: GUM_academic_epistemic-24
File: en_gum-ud-train, Sent #131: GUM_academic_epistemic-26
File: en_gum-ud-train, Sent #136: GUM_academic_epistemic-31
File: en_gum-ud-train, Sent #171: GUM_academic_games-28
File: en_gum-ud-train, Sent #343: GUM_academic_replication-10
File: en_gum-ud-train, Sent #352: GUM_academic_replication-19
File: en_gum-ud-train, Sent #356: GUM_academic_replication-23
File: en_gum-ud-train, Sent #357: GUM_academic_replication-24
File: en_gum-ud-train, Sent #409: GUM_academic_thrones-10
File: en_gum-ud-train, Sent #462: GUM_bio_bernoulli-33
File: en_gum-ud-train, Sent #509: GUM_bio_enfant-6
File: en_gum-ud-train, Sent #661: GUM_bio_gordon-13
File: en_gum-ud-train, Sent #743: GUM_bio_higuchi-29
File: en_gum-ud-train, Sent #982: GUM_bio_nida-35
File: en_gum-ud-train, Sent #1704: GUM_fiction_garden-16
File: en_gum-ud-train, Sent #1729: GUM_fiction_garden-41
File: en_gum-ud-train, Sent #1750: GUM_fiction_giants-18
File: en_gum-ud-train, Sent #1862: GUM_fiction_oversite-18
File: en_gum-ud-train, Sent #1872: GUM_fiction_oversite-28
File: en_gum-ud-train, Sent #1886: GUM_fiction_oversite-42
File: en_gum-ud-train, Sent #1886: GUM_fiction_oversite-42
File: en_gum-ud-train, Sent #1886: GUM_fiction_oversite-42
File: en_gum-ud-train, Sent #1932: GUM_fiction_pag-22
File: en_gum-ud-train, Sent #2109: GUM_fiction_rose-30
File: en_gum-ud-train, Sent #2325: GUM_interview_ants-10
File: en_gum-ud-train, Sent #2362: GUM_interview_ants-47
File: en_gum-ud-train, Sent #2472: GUM_interview_cocktail-23
File: en_gum-ud-train, Sent #2526: GUM_interview_daly-19
File: en_gum-ud-train, Sent #2550: GUM_interview_daly-43
File: en_gum-ud-train, Sent #2587: GUM_interview_dungeon-31
File: en_gum-ud-train, Sent #2743: GUM_interview_licen-19
File: en_gum-ud-train, Sent #2765: GUM_interview_mcguire-14
File: en_gum-ud-train, Sent #2781: GUM_interview_mcguire-30
File: en_gum-ud-train, Sent #2879: GUM_interview_messina-35
File: en_gum-ud-train, Sent #2929: GUM_interview_onion-14
File: en_gum-ud-train, Sent #2958: GUM_interview_onion-43
File: en_gum-ud-train, Sent #2985: GUM_interview_peres-4
File: en_gum-ud-train, Sent #3030: GUM_interview_peres-49
File: en_gum-ud-train, Sent #3097: GUM_interview_shalev-39
File: en_gum-ud-train, Sent #3099: GUM_interview_shalev-41
File: en_gum-ud-train, Sent #3106: GUM_interview_shalev-48
File: en_gum-ud-train, Sent #3185: GUM_interview_stardust-56
File: en_gum-ud-train, Sent #3198: GUM_news_asylum-9
File: en_gum-ud-train, Sent #3448: GUM_news_ie9-13
File: en_gum-ud-train, Sent #3541: GUM_news_taxes-6
File: en_gum-ud-train, Sent #3579: GUM_news_warhol-17
File: en_gum-ud-train, Sent #3674: GUM_news_warming-26
File: en_gum-ud-train, Sent #4171: GUM_voyage_chatham-16
File: en_gum-ud-train, Sent #4176: GUM_voyage_chatham-21
File: en_gum-ud-train, Sent #4255: GUM_voyage_cuba-17
File: en_gum-ud-train, Sent #4316: GUM_voyage_fortlee-43
File: en_gum-ud-train, Sent #4316: GUM_voyage_fortlee-43
File: en_gum-ud-train, Sent #4460: GUM_voyage_lodz-12
File: en_gum-ud-train, Sent #4470: GUM_voyage_lodz-22
File: en_gum-ud-train, Sent #4480: GUM_voyage_lodz-32
File: en_gum-ud-train, Sent #4681: GUM_voyage_tulsa-11
File: en_gum-ud-train, Sent #4775: GUM_voyage_york-27
File: en_gum-ud-train, Sent #4786: GUM_whow_arrogant-6
File: en_gum-ud-train, Sent #4807: GUM_whow_arrogant-27
File: en_gum-ud-train, Sent #5045: GUM_whow_cupcakes-45
File: en_gum-ud-train, Sent #5153: GUM_whow_flirt-25
File: en_gum-ud-train, Sent #5282: GUM_whow_languages-56
File: en_gum-ud-train, Sent #5359: GUM_whow_parachute-12
File: en_gum-ud-train, Sent #5549: GUM_whow_quinoa-24
File: en_gum-ud-train, Sent #5590: GUM_whow_quinoa-65

![Example](https://user-images.githubusercontent.com/76220465/165774453-0e54bcd0-48e7-47be-898a-76268f58a9c6.PNG)

- Sentences, where the non-projective dependency is a 'cc' and the head, is a 'conj'

File: en_gum-ud-dev, Sent #99: GUM_bio_emperor-22
File: en_gum-ud-dev, Sent #422: GUM_interview_gaming-13
File: en_gum-ud-dev, Sent #425: GUM_interview_gaming-16
File: en_gum-ud-dev, Sent #442: GUM_interview_gaming-33
File: en_gum-ud-dev, Sent #461: GUM_news_homeopathic-10
File: en_gum-ud-dev, Sent #554: GUM_speech_impeachment-39
File: en_gum-ud-dev, Sent #689: GUM_voyage_athens-24
File: en_gum-ud-test, Sent #286: GUM_fiction_falling-25
File: en_gum-ud-train, Sent #45: GUM_academic_census-17
File: en_gum-ud-train, Sent #669: GUM_bio_gordon-21
File: en_gum-ud-train, Sent #1713: GUM_fiction_garden-25
File: en_gum-ud-train, Sent #1729: GUM_fiction_garden-41
File: en_gum-ud-train, Sent #1908: GUM_fiction_oversite-64
File: en_gum-ud-train, Sent #2010: GUM_fiction_pag-100
File: en_gum-ud-train, Sent #2207: GUM_fiction_sneeze-83
File: en_gum-ud-train, Sent #2363: GUM_interview_ants-48
File: en_gum-ud-train, Sent #2435: GUM_interview_chomsky-31
File: en_gum-ud-train, Sent #2577: GUM_interview_dungeon-21
File: en_gum-ud-train, Sent #2616: GUM_interview_dungeon-60
File: en_gum-ud-train, Sent #2813: GUM_interview_mckenzie-13
File: en_gum-ud-train, Sent #3011: GUM_interview_peres-30
File: en_gum-ud-train, Sent #3458: GUM_news_ie9-23
File: en_gum-ud-train, Sent #4171: GUM_voyage_chatham-16
File: en_gum-ud-train, Sent #4353: GUM_voyage_guadeloupe-18
File: en_gum-ud-train, Sent #4681: GUM_voyage_tulsa-11
File: en_gum-ud-train, Sent #5235: GUM_whow_languages-9
File: en_gum-ud-train, Sent #5249: GUM_whow_languages-23
File: en_gum-ud-train, Sent #5254: GUM_whow_languages-28

![Capture2](https://user-images.githubusercontent.com/76220465/165775071-3aef589d-ad3a-4aaa-9dae-dd86526d2e87.PNG)

- Sentences, where the non-projective dependency is a 'case' and the head, is a 'flat'

File: en_gum-ud-dev, Sent #410: GUM_interview_gaming-1

![Capture3](https://user-images.githubusercontent.com/76220465/165775479-34f2e50c-ceab-4d85-9b99-44c586d312fc.PNG)

**Comment by nschneid** [comment]
I think the Del Frisco's example is from EWT.

**Comment by amir-zeldes** [comment]
Thanks for reporting, but are you sure you're looking at the dev branch? I just checked three of the sentences you pointed out and they did not contain those errors. For example dev branch of `GUM_whow_mice-11` looks like this:

![image](https://user-images.githubusercontent.com/2188635/165787808-d3942f0f-6a55-4afa-a640-a87f1af291fa.png)

I think I remember that error you're reporting, but it was fixed a while ago, after it was reported in #41 (which will be closed once UD 2.10 is released)

**Comment by amir-zeldes** [comment]
Sure, np
