### ISSUE TITLE
NumType=Card for 1/2

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-GUM#49]
I would expect this to be NumType=Frac, similar to 0.5

I also wonder if there's a different NumForm which would be more appropriate than Word, maybe even Digit.  This would apply to both `1/2` and `½`, eg

```
8       ½       ½       NUM     CD      NumForm=Word|NumType=Frac
```

There are also a couple numbers with no NumForm which appear to be Word, although they are tagged NNP instead of CD

```
12      Seven   Seven   NUM     NNP     Number=Sing|NumType=Card
15      Seven   Seven   NUM     NNP     Number=Sing|NumType=Card
21      Three   Three   NUM     NNP     Number=Sing|NumType=Card
```

Also could use NumForm, words of this type:

```
3       half    half    NOUN    NN      Number=Sing|NumType=Frac
1       Twice   twice   ADV     RB      NumType=Mult
```

**Comment by amir-zeldes** [comment]
Done!
