### ISSUE TITLE
feature Typo=Yes

### ISSUE THREAD

**Issue by bguil** [UniversalDependencies/UD_English-GUM#5]
In UD_English-GUM, the `Typo=Yes` feature is in the MISC column ([example](https://github.com/UniversalDependencies/UD_English-GUM/blob/ce2c1789123eb7b51258081a6a64520f5196a88c/en_gum-ud-test.conllu#L396)), but according to https://universaldependencies.org/u/overview/typos.html, it should be in the FEATS column.

**Comment by amir-zeldes** [comment]
Oh, thanks for pointing this out! I can correct it for the upcoming release.

**Comment by amir-zeldes** [comment]
Fixed in amir-zeldes/gum@f5310a4
