### ISSUE TITLE
to be verb features for collective nouns

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-GUM#51]
Wondering if this is intended or a mistake:

```
# sent_id = GUM_academic_implicature-2
# text = We hypothesized that the children, who were over the age of six at the time of collection, would have adult-like SI interpretations.
8	were	be	VERB	VBD	Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin	5	acl:relcl	5:acl:relcl	_
```

I would think `Number=Plur` in this case.  Later in the sentence, `would` does get a `Plur` feature

**Comment by amir-zeldes** [comment]
It's a mistake. This particular case is possibly avoidable by assuming that "were" is generally plural (though in hypotheticals it can also be a singular past subjunctive). The general problem is that "who", the subject of the relative clause, does not indicate number, so it defaults to the more frequent `Sing`. We could also fix this one case manually, but I think for now I'll just add a rule which assumes that 'were' is plural if there is no plural subject. Thanks for reporting!

**Comment by nschneid** [comment]
if there is no singular subject?

The alternative would be to follow the `ref` edge from "who" to find the antecedent and use its number.

**Comment by amir-zeldes** [comment]
> if there is no singular subject?

Yes, sorry!

> The alternative would be to follow the ref edge from "who" to find the antecedent and use its number.

You're right, that's better - it looks like there are 52 such cases in the corpus...

https://corpling.uis.georgetown.edu/annis/#_q=cG9zPS9OLipTLyAtPmVkZXBbZnVuYz0icmVmIl0gdG9rX2Z1bmM9Im5zdWJqIiAmIHBvcz0vVi5ELyAmICMzIC0-ZGVwICMy&_c=R1VN&cl=5&cr=5&s=0&l=10

**Comment by AngledLuffa** [comment]
Was this resolved?

**Comment by amir-zeldes** [comment]
No, looks like I'd forgotten to implement this - I think I have a working fix now though, should propagate on the next build!
