### ISSUE TITLE
Don't you verb!

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/UD_English-GUM#6]
@nschneid @sebschu any opinions on: "don't you worry!"

nsubj(worry, you)

Or:

vocative(worry, you)

?

**Comment by nschneid** [comment]
nsubj. It can be combined with a vocative: "Don't you worry, John!"

**Comment by amir-zeldes** [comment]
OK - we can adopt this analysis since it has two votes already, though just as devil's advocate, consider:

  * You can generally have more than one vocative, so combinability with another vocative isn't decisive: "John, don't do it you rascal!"
  * Imperatives don't usually have `nsubj`, so this would be a big exception (I assume here if it's nsubj it's somehow subject of the infinitive, but of course in UD this is not really visible, since "do" is `aux` and could never host the subject anyway)

**Comment by nschneid** [comment]
>  * You can generally have more than one vocative, so combinability with another vocative isn't decisive: "John, don't do it you rascal!"

But you can't substitute vocative "John" for "you":

- *Don't John worry!

And a vocative after an auxiliary or copula would be unusual I think:

- Don't you worry, John! / *Don't John you worry!
- Are you ready, John? / *Are John you ready?
- Have you eaten yet, John? / *Have John you eaten yet?

Rather, the idiom can be considered a case of subject-auxiliary inversion. Goldberg (2006) has an analysis of SAI constructions for various non-declarative sentence types.

>  * Imperatives don't usually have `nsubj`, so this would be a big exception (I assume here if it's nsubj it's somehow subject of the infinitive, but of course in UD this is not really visible, since "do" is `aux` and could never host the subject anyway)

True, usually it's unnecessary—but I don't know that it would be _ungrammatical_ for imperatives to have a "you" subject. I'm imagining colloquial sentences like "You stop talking right this minute!". (Not vocative IMO.)

**Comment by dan-zeman** [comment]
I agree that it is quite strange to have a subject of an imperative – this has not occurred to me at first! But even if it makes me less decided about the `nsubj` option, it does not make me think that the `vocative` option is great, so I think I'm still leaning towards `nsubj`, at least until I see more arguments in favor of `vocative`.

**Comment by jnivre** [comment]
I definitely support the nsubj analysis. Imperatives (marginally) take subjects in the same way in Swedish, and there are a number of criteria (some of them prosodic) to distinguish them from vocatives. The English construction appears to be parallel. Note, for example, that the subject of an imperative has to be in the second person, which the vocative doesn't have to be:

You, don't worry!
Dan, don't worry!
Don't you worry!
*Don't Dan worry!

**Comment by amir-zeldes** [comment]
Thanks everyone - I've also asked for input from my colleague Ruth Kramer, who is a theoretical syntactician. She supports the `nsubj` analysis and pointed me to this paper arguing for imperative subjects in some constructions:

https://link.springer.com/article/10.1007/s11049-007-9029-6

We'll be sure to apply this analysis for the upcoming winter release of GUM V7 (brand new genres and data!)
