### ISSUE TITLE
obl:agent tags are recognized as obl 

### ISSUE THREAD

**Issue by DnVS97** [UniversalDependencies/UD_English-GUM#63]
Hi, I'm using the UD_English-GUM udpipe 2.5 downloaded from [here](https://github.com/jwijffels/udpipe.models.ud.2.5/blob/master/inst/udpipe-ud-2.5-191206/english-gum-ud-2.5-191206.udpipe). When tagging sentences using the [udpipe R](https://cran.r-project.org/web/packages/udpipe/index.html) library, I've noticed that the _obl:agent_ tag is not used while in this [UD comparison](https://universaldependencies.org/treebanks/en-comparison.html) overview, it is noted that the GUM treebank does have this tag. In the cases where this tag should be assigned, the _obl_ tag is used. 

The example sentences that I've used to test are the following and are found [here ](https://universaldependencies.org/id/dep/obl-agent.html)on the universal dependencies website:
"shaped by tectonic forces"
"the-book that loved by him"
"She had been warned by Mother before ."
"Prize was awarded by-dean of-faculty ."

I have also used the 2.3 udpipe version of the GUM Treebank but the similar problem occurs: the _obl:agent_ tag is replaced by the _obl_ tag. I'm wondering: is there something that I'm missing regarding the _obl:agent_ tag? For my specific use case I'm interested in this tag. 

Thanks in advance!

**Comment by martinpopel** [comment]
The relation `obl:agent` first appeared in UD_English-GUM version 2.10 (released on May 15, 2022). It is not present in the previous versions, including 2.5 on which the UDPipe model is trained.
I am afraid that the [UDPipe 2.10 modes](https://ufal.mff.cuni.cz/udpipe/2/models#universal_dependencies_210_models) are not available in the R wrapper yet.

**Comment by DnVS97** [comment]
Thanks for the quick reply!
