### ISSUE TITLE
Odd uses of `fixed`

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/UD_English-GUM#67]
`GUM_academic_implicature-15`:

> In a future study, it is also important to consider if additional training in the difference between reporting on felicity and truth value judgments would impact results, or if more naturalistic experimental conditions (e.g., demonstrating actions using real objects instead of two-dimensional depictions) would be beneficial.

![image](https://github.com/UniversalDependencies/UD_English-GUM/assets/449545/1c5e3a3e-57db-4efd-aebf-2ec7d1ee49ae)

There are a few other instances of `fixed` like this too, e.g. `GUM_academic_implicature-18`.

**Comment by amir-zeldes** [comment]
Thanks for reporting, but I'm not sure where you are seeing the data in this form. In the repo I see the `fixed` edge attached correctly for this sentence:

https://github.com/UniversalDependencies/UD_English-GUM/blob/master/not-to-release/sources/GUM_academic_implicature.conllu#L478
```CoNLL-U
41	using	use	VERB	VBG	VerbForm=Ger	40	acl	40:acl	Discourse=mode-means:44->43:0
42	real	real	ADJ	JJ	Degree=Pos	43	amod	43:amod	Entity=(73-object-new-cf8-2-sgl
43	objects	object	NOUN	NNS	Number=Plur	41	obj	41:obj	Entity=73)
44	instead	instead	ADV	RB	_	49	case	49:case	_
45	of	of	ADP	IN	_	44	fixed	44:fixed	_
46	two	two	NUM	CD	NumForm=Word|NumType=Card	48	nummod	48:nummod	Entity=(74-object-new-cf11-4-sgl|SpaceAfter=No|XML=<w>
47	-	-	PUNCT	HYPH	_	46	punct	46:punct	SpaceAfter=No
48	dimensional	dimensional	ADJ	JJ	Degree=Pos	49	amod	49:amod	XML=</w>
49	depictions	depiction	NOUN	NNS	Number=Plur	39	obl	39:obl:instead_of	Entity=74)|SpaceAfter=No
```

Is this maybe the result of some converter or other tool running over the data? Or are you looking at it in a different repo?

**Comment by ftyers** [comment]
Wow, looks like I was looking at an ancient version, from 2018! Disregard this :)
