### ISSUE TITLE
Entity nested into itself

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/UD_English-GUM#7]
In the following sentence, there are two mentions of the same entity with ID `time-23`. What is unusual is that they are nested:
first: "*substantial periods (months to years) of limited or no exposure following L2 training*"
second: "*months to years*"
Is this intended/correct?
Does GUM format allow non-continuous span of mentions (e.g. `MentionSpan=4-5,11-18`, i.e. "*substantial periods of limited or no exposure following L2 training*")?
Does GUM allow annotating bridging relations?
Is there a validator for the `Entity` markup?

```
# sent_id = GUM_academic_exposure-6
# text = In fact, substantial periods (months to years) of limited or no exposure following L2 training are not uncommon, and may even be the norm [16].
# s_type = multiple
1	In	in	ADP	IN	_	2	case	_	Discourse=justify:15->14
2	fact	fact	NOUN	NN	Number=Sing	21	obl	_	SpaceAfter=No
3	,	,	PUNCT	,	_	2	punct	_	_
4	substantial	substantial	ADJ	JJ	Degree=Pos	5	amod	_	Entity=(time-23
5	periods	period	NOUN	NNS	Number=Plur	21	nsubj	_	_
6	(	(	PUNCT	-LRB-	_	7	punct	_	Discourse=elaboration:16->15|SpaceAfter=No
7	months	month	NOUN	NNS	Number=Plur	5	appos	_	Entity=(time-23
8	to	to	ADP	IN	_	9	case	_	_
9	years	year	NOUN	NNS	Number=Plur	7	nmod	_	Entity=time-23)|SpaceAfter=No
10	)	)	PUNCT	-RRB-	_	7	punct	_	_
11	of	of	ADP	IN	_	15	case	_	Discourse=same-unit:17->15
12	limited	limited	ADJ	JJ	Degree=Pos	15	amod	_	Entity=(abstract-24
13	or	or	CCONJ	CC	_	14	cc	_	_
14	no	no	PRON	DT	Polarity=Neg	12	conj	_	_
15	exposure	exposure	NOUN	NN	Number=Sing	5	nmod	_	Entity=abstract-24)
16	following	follow	VERB	VBG	VerbForm=Ger	15	acl	_	Discourse=elaboration:18->15
17	L2	L2	NOUN	NN	Number=Sing	18	compound	_	Entity=(event-25(abstract-3)
18	training	training	NOUN	NN	Number=Sing	16	obj	_	Entity=time-23)event-25)
19	are	be	AUX	VBP	Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin	21	cop	_	Discourse=same-unit:19->15
20	not	not	PART	RB	Polarity=Neg	21	advmod	_	_
21	uncommon	uncommon	ADJ	JJ	Degree=Pos|Polarity=Neg	0	root	_	SpaceAfter=No
22	,	,	PUNCT	,	_	28	punct	_	_
23	and	and	CCONJ	CC	_	28	cc	_	Discourse=joint:20->15
24	may	may	AUX	MD	VerbForm=Fin	28	aux	_	_
25	even	even	ADV	RB	_	28	advmod	_	_
26	be	be	AUX	VB	VerbForm=Inf	28	cop	_	_
27	the	the	DET	DT	Definite=Def|PronType=Art	28	det	_	Entity=(abstract-26
28	norm	norm	NOUN	NN	Number=Sing	21	conj	_	Entity=abstract-26)
29	[	[	PUNCT	-LSB-	_	30	punct	_	Discourse=evidence:21->15|SpaceAfter=No
30	16	16	NUM	CD	NumForm=Digit|NumType=Card	21	dep	_	Entity=(abstract-27)|SpaceAfter=No
31	]	]	PUNCT	-RSB-	_	30	punct	_	SpaceAfter=No
32	.	.	PUNCT	.	_	21	punct	_	_
```

**Comment by amir-zeldes** [comment]
Yes, this is by design. Most coref annotated corpora allow nesting in certain scenarios, including the main benchmark corpus, OntoNotes. Here we have a nested appositive coref, though you can only see the coref type in the source data here:

https://github.com/amir-zeldes/gum/blob/master/coref/tsv/GUM_academic_exposure.tsv#L124

Some datasets have different guidelines on when to do this, but almost all include pronominal anaphora cases like this, where the pronoun "her" is contained inside a relative clause modifying its antecedent:

```
15	a	a	DET	DT	Definite=Ind|PronType=Art	21	det	21:det	Entity=(person-68
16	lonely	lonely	ADJ	JJ	Degree=Pos	21	amod	21:amod	SpaceAfter=No
17	,	,	PUNCT	,	_	16	punct	16:punct	_
18	beautiful	beautiful	ADJ	JJ	Degree=Pos	21	amod	21:amod	SpaceAfter=No
19	,	,	PUNCT	,	_	18	punct	18:punct	_
20	young	young	ADJ	JJ	Degree=Pos	21	amod	21:amod	_
21	woman	woman	NOUN	NN	Number=Sing	13	nmod	13:nmod:among|24:nsubj	_
22	who	who	PRON	WP	PronType=Rel	24	nsubj	21:ref	Discourse=elaboration:62->61
23	has	have	AUX	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	24	aux	24:aux	_
24	lost	lose	VERB	VBN	Tense=Past|VerbForm=Part	21	acl:relcl	21:acl:relcl	_
25	her	her	PRON	PRP$	Gender=Fem|Number=Sing|Person=3|Poss=Yes|PronType=Prs	26	nmod:poss	26:nmod:poss	Entity=(person-69(person-68)
26	parents	parent	NOUN	NNS	Number=Plur	24	obj	24:obj	Entity=person-68)person-69)|SpaceAfter=No
```

If we didn't allow nesting, that "her" would remain unresolved.

**Comment by amir-zeldes** [comment]
Oh, and yes, GUM does contain bridging annotations, which are now also ported to the UD corpus. The format is described in the README in the UD dev branch. 

As for validation, there is a rather complex validation machinery in the GUM build bot. Most of it is in this script:

https://github.com/amir-zeldes/gum/blob/master/_build/utils/validate.py

But for coref some stuff also gets caught here:

https://github.com/amir-zeldes/gum/blob/master/_build/utils/repair_tsv.py

For some background about the GUM build bot if you want to understand what's happening, this is a good starting point:

https://corpling.uis.georgetown.edu/gum/build.html

**Comment by martinpopel** [comment]
Thanks for all the info. And thanks for GUM. I see a lot of effort has been invested in GUM and I like its rich annotation where the multiple layers seem to be developed jointly, thus hopefully improving consistency across the layers.

I am still not sure I understand the motivation behind GUM annotation guidelines regarding appositions.

Typically, there is no nesting, e.g. in `GUM_academic_exposure-2`: "adult-learned second language (L2)"
there are two mentions: "adult-learned second language" and "L2". The parenthesis symbols are not part of any mention.
This is intuitive and expected.
I guess "These are substantial periods (months to years)."
or "These are substantial periods of exposure (months to years)."
would be annotated in the same way, i.e. without nesting the mentions.

However, if the first mention continues after the second mention, as in "substantial periods (months to years) of exposure",
suddenly the apposition becomes part of the first mention. This seems inconsistent to me.
I guess this could be caused by the file format which does not allow allow to annotate non-continuous mentions.

> "young woman who has lost her parents"

Thanks for the example (which shows that nested mentions of the same entity are not as rare as I had thought).
I guess that a defining relative clauses is always part of the mention.
So even if "her" (or rather "herself") was the last word in the subtree headed by "woman", it would still be nested (i.e. part of both mentions).
So unlike the apposition rules, this is consistent.

**Comment by amir-zeldes** [comment]
That's right, the motivation for ending the nesting markable late in the modifier after the appositive ("of exposure"). It's true we could probably convert it to a format with discontinuous spans based on the syntax tree, but since current coref systems wouldn't be able to predict such spans, and it would complicate both the annotation interface and the format representation, we're not doing it at the moment. And as you see from the pronoun case, we need nesting coref anyway, so it hasn't been a big issue so far.
