### ISSUE TITLE
Incorrect lemmas for some RB tokens

### ISSUE THREAD

**Issue by rhdunn** [UniversalDependencies/UD_English-GUM#75]
The following lemma is incorrectly lemmatized:
```
ERROR: Sentence GUM_news_iodine-3 token 10 -- RB lemma 'mild' is not the lowercase form 'mildly' text
```

The following lemmas should be lower case:
```
ERROR: Sentence GUM_voyage_oakland-27 token 1 -- RB lemma 'South' is not the lowercase form 'South' text
ERROR: Sentence GUM_conversation_family-53 token 1 -- RB lemma 'Out' is not the lowercase form 'Out' text
ERROR: Sentence GUM_conversation_family-54 token 1 -- RB lemma 'Out' is not the lowercase form 'Out' text
```

The following lemmas are flagged because the `CorrectForm` contains multiple words:
```
ERROR: Sentence GUM_academic_lighting-12 token 26 -- RB lemma 'well' is not the lowercase form 'well as' text
ERROR: Sentence GUM_interview_mckenzie-27 token 3 -- RB lemma 'really' is not the lowercase form 'a really' text
ERROR: Sentence GUM_speech_floyd-36 token 10 -- RB lemma 'profoundly' is not the lowercase form 'are profoundly' text
ERROR: Sentence GUM_vlog_covid-46 token 19 -- RB lemma 'really' is not the lowercase form 'a really' text
ERROR: Sentence GUM_vlog_wine-12 token 8 -- RB lemma 'naturally' is not the lowercase form 'a naturally' text
ERROR: Sentence GUM_whow_languages-29 token 7 -- RB lemma 'not' is not the lowercase form 'are not' text
```

**Comment by amir-zeldes** [comment]
In the first case I don't think it's quite right to say that the lemma is "mildly". The sentence reads:

  * school children are mild to moderately iodine deficient

And the target hypothesis says it should be "mildly" in standard English. So it's the wrong choice of word, but it is properly an occurrence of 'mild', so I think 'mild' is also the correct lemma (for an arguably incorrectly chosen word)

The middle group has genuine errors, will fix. The last one is an issue with how `<sic ana="..">` works, i.e. the discrepancy between the notion of target hypothesis and the conllu Typo annotation. Unless there is a good alternative suggestion (which is ideally automatable), I will leave those alone.

**Comment by rhdunn** [comment]
With "mild" it is annotated with `Typo=Yes` and `CorrectForm=mildly|XML=<sic ana::"mildly"></sic>` so it has been corrected to "mildly". As a result the lemma should be "mildly" to be consistent with the corrected form annotation. Otherwise, it shouldn't be annotated as a typo with a corrected form if the lemma matches the `FORM` field.
