### ISSUE TITLE
Is this "yours" also genitive case?  (Maybe none of them?)

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-GUM#76]
Two examples of `yours` are genitive:

```
# sent_id = GUM_vlog_exams-136
# text = The floor is yours.
4       yours   yours   PRON    PRP$    Case=Gen|Number=Sing|Person=2|Poss=Yes|PronType=Prs     0       root    0:root  Entity=(106-person-giv:inact-cf1-1-ana)|SpaceAfter=No
```

```
# sent_id = GUM_vlog_pizzeria-62
# text = You want onions on yours?
5       yours   yours   PRON    PRP$    Case=Gen|Number=Sing|Person=2|Poss=Yes|PronType=Prs     2       obl     2:obl:on        Entity=(25-person-giv:act-cf1-1-ana)|SpaceAfter=No
```

This one is different:

```
# sent_id = GUM_whow_languages-6
# s_prominence = 3
# s_type = decl
# transition = continue
# text = The choice is all yours.
1       The     the     DET     DT      Definite=Def|PronType=Art       2       det     2:det   Discourse=restatement-partial:8->5:2:ref-prs-22,57|Entity=(12-event-acc:com-cf2-2-sgl
2       choice  choice  NOUN    NN      Number=Sing     5       nsubj   5:nsubj Entity=12)
3       is      be      AUX     VBZ     Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   5       cop     5:cop   _
4       all     all     ADV     RB      Degree=Pos      5       advmod  5:advmod        _
5       yours   your    PRON    PRP     Number=Sing|Person=2|Poss=Yes|PronType=Prs      0       root    0:root  Entity=(5-person-giv:act-cf1*-1-ana)|SpaceAfter=No
6       .       .       PUNCT   .       _       5       punct   5:punct _
```

**Comment by AngledLuffa** [comment]
A past PR on the Pronouns dataset had removed its genitive cases:

https://github.com/UniversalDependencies/UD_English-Pronouns/pull/5

but there are quite a few `Case=Gen` in EWT

**Comment by AngledLuffa** [comment]
Also, the lemmas of `yours` don't agree with the current PRON table:

https://universaldependencies.org/en/pos/PRON.html

**Comment by amir-zeldes** [comment]
The root cause is that this is an xpos tag error - PRP$ should be PRP. Will fix, thanks!

**Comment by AngledLuffa** [comment]
Didn't even look at that, nice catch.  Still, might be worth rechecking the features as well

**Comment by amir-zeldes** [comment]
The features are auto generated based on the manual annotations, and in this case the culprit is the xpos tag (and the lemma would have tripped the validator if xpos had been correct)

**Comment by AngledLuffa** [comment]
What I mean is maybe none of them should be `Case=Gen` according to the PRON page 

https://universaldependencies.org/en/pos/PRON.html

**Comment by amir-zeldes** [comment]
Indeed, as long as they are not `xpos=PRP$`, they will also not be `Case=Gen`:

https://github.com/amir-zeldes/gum/blob/master/_build/utils/ud_morph.ini#L59

**Comment by AngledLuffa** [comment]
The first couple examples in this thread were `Case=Gen`, but perhaps you mean it will change now

**Comment by amir-zeldes** [comment]
Yup, that will change automatically. Almost all FEATS in GUM are refreshed and generated automatically with each release, so there is no need to correct them manually.

**Comment by rueter** [comment]
> 
> ```
> # sent_id = GUM_vlog_pizzeria-62
> # text = You want onions on yours?
> 5       yours   yours   PRON    PRP$    Case=Gen|Number=Sing|Person=2|Poss=Yes|PronType=Prs     2       obl     2:obl:on        Entity=(25-person-giv:act-cf1-1-ana)|SpaceAfter=No
> ```
Here _yours_ should not be labled *Case=Gen*, unless the adposition takes genitive goverment.
Lemmatization looks correct if we consider function. @amir-zeldes

**Comment by amir-zeldes** [comment]
> Here yours should not be labled Case=Gen

Indeed, and now that the underying xpos has been changed to PRP it will not happen - as soon as FEATS are regenerated, it will not be Case=Gen anymore.

> Lemmatization looks correct if we consider function

No, it was decided to split these and the personal pronouns into exactly two lemmas - the attributive possessive form for all the possessives (your, yours -> your) and the nominative personal pronoun for the rest (you), so the correct lemma is "your" (as now corrected upstream). See the whole specification here:

https://universaldependencies.org/en/pos/PRON.html
