### ISSUE TITLE
Annotation errors for relative clauses

### ISSUE THREAD

**Issue by xiulinyang** [UniversalDependencies/UD_English-GUM#77]
(Sorry, I opened the issue in the wrong repository earlier before.) The following sentences should not be taken as relative clauses or the _acl:relcl_ is assigned to the wrong token. 

- Who 's the party being s- served ?
- Runs batted in 171
- Unique tree carvings done by the peaceful Moriori people hundreds of years ago
- After the exchange of fire, North Korea stated it would attack any loudspeakers broadcasting propaganda and would respond, militarily, within 48 hours if the broadcasts do not stop.
- When he became chairman of this city committee, there were 300,000 more Republicans registered in the city of Philadelphia than Democrats, and it is a source of satisfaction to me that tonight there are 260,000 more Democrats registered.
- Rathke also asked the governments of South East Asia not to turn away boats of people seeking asylum
- So , I assumed oh that like maybe it was just like a sore throat gotten because I did n't bother to you know blow dry my hair .
- Last week, I read 2,300 Humvees — these are big vehicles — were left behind for the enemy.
- And the way it's marketed, and the way we're d- — we develop needs for it. (_d-_ should be _[reparandum](https://universaldependencies.org/u/dep/reparandum.html)_)
- In this case , the excellent advice offered by your instructors on assisting chute opening may be of assistance to you .
- Spiritually and culturally important to Moriori , it holds the last known concentration of momori - rakau , or tree carvings done by the ancestors of today 's Moriori .
- Photos released of the scene showed numerous bloodied bodies and various scattered debris .
- I note with great pleasure the freedom to re-purpose offered by openly licensed educational resources , the convenience that online access to **learners** as alternative courses delivery and certification methods .

The part of speech for _cross_ is wrong. 
- We don’t have any rules or known lines we won’t cross.

**Comment by nschneid** [comment]
> I note with great pleasure the freedom to re-purpose offered by openly licensed educational resources , the convenience that online access to **learners** as alternative courses delivery and certification methods .

I don't actually see "that" in the treebank:

> I note with great pleasure the freedom to re-purpose offered by openly licensed educational resources, the convenience online access to learners as alternative courses delivery and certification methods. 

One interpretation is that "of" is missing after "convenience". (In EWT I have started indicating such inferable missing words on the previous word in MISC: `MissingWordsAfter=of`.)

Another interpretation is that a verb like "provides" is missing at the end. But "access" would be the head of "learners" even in this case.

I can't think of an interpretation that supports acl:relcl(convenience, learners).

**Comment by xiulinyang** [comment]
> Can you explain the error in this sentence? I don't see acl:relcl there: "When he became chairman of this city committee,..."
I rechecked the sentence and now I feel like the annotation is correct. Sorry!

> I don't actually see "that" in the treebank:
Yes, probably I copied the sentence with the added 'that' but forgot to remove it. 

By the way, in the sentence  _It was a tournament that I wish we'd actually gone back to more often_, the pos tags for might be wrong.

**Comment by nschneid** [comment]
The Philadelphia sentence has 3 distinct uses of "that". Would make a good exam question. :)
