### ISSUE TITLE
around as an ADP?

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-GUM#81]
Is it a mistag?  I would think this instance of `around` is an `ADP`.

```
# sent_id = GUM_vlog_covid-28
16      results result  NOUN    NNS     Number=Plur     14      obj     14:obj  Entity=49)|MSeg=result-s
17      which   which   PRON    WDT     PronType=Rel    21      nsubj   10:ref  Discourse=elaboration-attribute:76->74:1:syn-relcl-521,525
18      was     be      AUX     VBD     Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin   21      cop     21:cop  _
19      around  around  ADV     RB      Degree=Pos      21      advmod  21:advmod       Entity=(48-time-giv:act-cf3-3-coref|MSeg=a-round
20      like    like    INTJ    UH      _       21      discourse       21:discourse    _
21      6:00    6:00    NUM     CD      NumForm=Digit|NumType=Card      10      acl:relcl       10:acl:relcl    XML=<time when:::"18:00:00">
22      pm      p.m.    NOUN    NN      Number=Sing     21      nmod:tmod       21:nmod:tmod    Entity=48)48)|SpaceAfter=No|XML=</time>
23      .       .       PUNCT   .       _       7       punct   7:punct _
```

Also, in general I find myself wondering why `around` is never an `RP` in the XPOS this treebank, such as `open up_RP` vs `come around_RB` or `close around_RB`.  Although it's not very consistent in PTB to label `around` as `RP` vs `RB` in `turn around`, `get around`, etc, it looks like `RP` is more common.  However, `this time around_RP`, `last time around_RP` is consistent.  Even `this time around` isn't 100% consistent, though

```
                 (NP
                    (NP
                      (ADJP (RB even) (JJR more) )
                      (NN caution) )
                    (PP (IN than)
                      (NP (DT the) (JJ first) (NN time) (RB around) ))))))))
```

**Comment by nschneid** [comment]
"which was **around** like 6:00 pm" should be ADP, yes.

The idiom "this time around" (more generally "X time around") is interesting. My gut feeling is that "around" can be omitted so it is a modifier, presumably RB/ADV/advmod.

If memory serves RP should be aligned with [`compound:prt`](https://universaldependencies.org/en/dep/compound-prt.html), which (unfortunately IMO) is defined in terms of idiomaticity. "come around" would presumably be RB/ADV/advmod if it is purely spatial and RP/ADP/compound:prt in the idiomatic meaning of 'change to my preferred opinion'.
