### ISSUE TITLE
Empty nodes incorrectly part of mention spans

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/UD_English-GUM#84]
In GUM_fiction_lunre-18, we see a mention of type `person`, but it includes a verbal empty node 18.1 ("appeared"), which clearly should not be part of the mention span (the span should be discontinuous):
```CoNLL-U
17      another another DET     DT      PronType=Ind    18      det     18:det  Entity=(2-person-giv:inact-cf3-2-coref|MSeg=an-other
18      man     man     NOUN    NN      Number=Sing     6       conj    18.1:nsubj      SpaceAfter=No
18.1    appeared        appear  VERB    VBD     Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin   _       _       6:conj:and      CopyOf=6
19      ,       ,       PUNCT   ,       _       20      punct   20:punct        _
20      tall    tall    ADJ     JJ      Degree=Pos      18      amod    18:amod _
21      and     and     CCONJ   CC      _       22      cc      22:cc   _
22      lean    lean    ADJ     JJ      Degree=Pos      20      conj    18:amod|18.1:amod|20:conj:and   SpaceAfter=No
23      ,       ,       PUNCT   ,       _       27      punct   27:punct        _
24      astride astride ADP     IN      _       27      case    27:case MSeg=a-stride
25      an      a       DET     DT      Definite=Ind|PronType=Art       27      det     27:det  Entity=(78-animal-new-cf6-3-coref
26      island  island  NOUN    NN      Number=Sing     27      compound        27:compound     Entity=(79-place-new-cf7-1-sgl)
27      mule    mule    NOUN    NN      Number=Sing     18      nmod    18:nmod:astride Entity=78)2)|SpaceAfter=No
```

Similarly, in GUM_interview_hill-35, empty node 25.1 ("supported") should not be part of the George_W._Bush mention span.

In these two cases, the verbal empty node becomes the head of the mention after conversion to CorefUD (so these are two of three zero mentions in CorefUD GUM), but the problem is not the head-detection code, but the fact that the verb (which is the "highest" node in the mention in the enhanced dependencies) is included in the span.

There may be many other cases where the span should be discontinues.

**Comment by nschneid** [comment]
For the example shown above, I think the problem in the tree is that the analysis is inconsistent between treating "tall and lean" and "astride an island mule" as depictive modifiers of the predicate (consistent with the ellipsis interpretation in the empty node) or as adnominal modifiers (consistent with their attachment to "man").

**Comment by martinpopel** [comment]
> treating "tall and lean" and "astride an island mule" as depictive modifiers of the predicate (consistent with the ellipsis interpretation in the empty node)

So in that case, the mention span should be just "another man" (nodes 17-18, excluding the empty node 18.1 and the depictive modifiers of the predicate) and "tall and lean" should depend on the empty nodes in the enhanced dependencies. Am I right?

We can imagine a different sentence: _"My father’s plaited umbrella appeared, his still, imposing figure, and beside him another man, **who was** tall and lean"_. Here, I have added an explicit copula "who was" which prevents the depictive-modifier-of-the-predicate reading. So the mention span should be _"another man, who was tall and lean"_. Perhaps we still want to add the empty node 18.1 "appeared", but it should not be part of the span. So in this case, we would need a discontinuous mention span. Am I right?

**Comment by amir-zeldes** [comment]
>  the analysis is inconsistent between treating "tall and lean" and "astride an island mule" as depictive modifiers of the predicate (consistent with the ellipsis interpretation in the empty node) or as adnominal modifiers (consistent with their attachment to "man")

Why is it inconsistent? The "appeared" empty node is compatible with the adnominal interpretation, it's just triggered by and + conj, since the actual predicate appears earlier and is not repeated. Here is the full sentence:

```CoNLL-U
1	My	_	_	_	_	2	nmod:poss	_	_
2	father	_	_	_	_	5	nmod:poss	_	_
3	’s	_	_	_	_	2	case	_	_
4	plaited	_	_	_	_	5	amod	_	_
5	umbrella	_	_	_	_	6	nsubj	_	_
6	appeared	_	_	_	_	0	root	_	_
7	,	_	_	_	_	12	punct	_	_
8	his	_	_	_	_	12	nmod:poss	_	_
9	still	_	_	_	_	12	amod	_	_
10	,	_	_	_	_	9	punct	_	_
11	imposing	_	_	_	_	12	amod	_	_
12	figure	_	_	_	_	6	conj	_	_
13	,	_	_	_	_	18	punct	_	_
14	and	_	_	_	_	18	cc	_	_
15	beside	_	_	_	_	16	case	_	_
16	him	_	_	_	_	18	orphan	18.1:obl:beside	_
17	another	_	_	_	_	18	det	_	_
18	man	_	_	_	_	6	conj	18.1:nsubj	_
18.1	appeared	appear	VERB	VBD	Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin	_	_	6:conj:and	CopyOf=6
19	,	_	_	_	_	20	punct	_	_
20	tall	_	_	_	_	18	amod	_	_
21	and	_	_	_	_	22	cc	_	_
22	lean	_	_	_	_	20	conj	_	_
23	,	_	_	_	_	27	punct	_	_
24	astride	_	_	_	_	27	case	_	_
25	an	_	_	_	_	27	det	_	_
26	island	_	_	_	_	27	compound	_	_
27	mule	_	_	_	_	18	nmod	_	_
28	.	_	_	_	_	6	punct	_	_
```

> a mention of type person, but it includes a verbal empty node 18.1 ("appeared")

No, GUM minspans never include empty nodes, and they are ignored in minspan token numbering. The coref data actually comes from a format and tool that don't know about the existence of empty nodes, see #85 (and we should probably continue the discussion on that topic there).

> So in this case, we would need a discontinuous mention span. Am I right?

Yes, that's correct, GUM does not represent discontinuous mention spans at the moment, we recently noted it as a desideratum in this paper: https://arxiv.org/abs/2410.01170 - adding @lauren-lizzy-levine who has been looking at mention and anaphora definitions in GUM

**Comment by nschneid** [comment]
If "tall and lean" is considered coordination with ellipsis, then the tree should be as if the clause were "Another man appeared, tall and lean", right? With "tall and lean" after the verb that's (depictive) advcl, not amod.

**Comment by nschneid** [comment]
Another option would be to move "appeared" after "mule"—"Another man, tall and lean, astride an island mule (appeared)." That would be consistent with the adnominal relations.

**Comment by amir-zeldes** [comment]
> "Another man, tall and lean, astride an island mule (appeared)."

I think that reconstruction just sounds less natural - if "appeared" had been uttered, I would imagine there would be extraposition of the post-posed modifier since it's so heavy compared to just the verb. But one of the arguments in #85 is in fact that empty nodes don't exactly have a clear cut linear position, so maybe this is just more evidence of that 🤔

**Comment by martinpopel** [comment]
As for the syntactic annotation of the whole sentence, I would perhaps annotate it as a simple coordination with three conjuncts (umbrella, figure, umbrella), so no empty node would be needed. In English, it may be rare to have a coordination depending on a verb that is position between the conjuncts (thus making the coordination non-projective) - I have found just one such (correctly annotated) example in English-GUM (GUM_academic_epistemic-25), but there are 174 such examples in Czech-PDT.
However, in this issue I am not concerned about the syntactic annotation. I wanted to discuss the issue what to do if there is (for whatever reason) an empty node within a mention span, which clearly does not belong to the mention span. I suggest the correct way is to exclude such empty node from the mention span (thus making the span discontinuous). The alternative is to expect that all empty nodes are somehow implicitly excluded from all mention spans (because these were annotated within different projects by different annotators who perhaps even did not know about the other project). I don't like the alternative for several reasons (most importantly: there are cases where the empty nodes clearly belong to the mention span and we want to distinguish these cases)
I understand it may take some time to fix these errors. I can help by showing the 5 cases in English-GUM where empty nodes are within a span, but some of their enhanced parents are outside the span. I could even provide a code that automatically excludes such nodes (and the whole subtree) from the mention span.

> GUM minspans never include empty nodes
Yes, minspans were discussed in #85 (now closed). But this issue is not about minspan, so this is not relevant.

**Comment by martinpopel** [comment]
Great. So I am closing this issue understanding that once discontinuous spans are supported in GUM, the "appeared" empty node will be excluded from the span (or it will be moved after the span as @nschneid suggested).
