### ISSUE TITLE
Non-projective coordinations with false preposition conjuncts

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/UD_English-GUM#86]
I've discovered 15 instances of coordinations where a second conjunct is attached non-projectively to the first conjunct, whereas the gap is caused by the parent of the first conjunct. In 12 instances, the first conjunct is a preposition. I think all these 12 instances are annotation errors. For example in GUM_bio_gordon-13: "_in Scotland or England_", _England_ is attached to _in_, but it should be attached to _Scotland_.
Here is [a visualization of the 12 trees](https://ufallab.ms.mff.cuni.cz/~popel/ud/gum-nonproj-coord-errors.html), generated using the following command:
```bash
cat universal-dependencies-2.15/UD_English-GUM/*.conllu | udapy -HM util.Mark \
 node='node.udeprel=="conj" and node.parent.parent<node and node.parent.parent>node.parent and node.parent.upos=="ADP"' \
 print_stats=1 > gum-nonproj-coord-errors.html
```

I can send a PR that would fix these errors, using 
```bash
udapy -s util.Eval node='if node.udeprel=="conj" and node.parent.parent<node and node.parent.parent>node.parent: node.parent = node.parent.parent' < in.conllu > out.conllu
```
but I know it should be rather fixed in the original GUM files.

Only in GUM_news_warhol-17, a manual fix will be needed ("_in 2007 and a second recently_" should be perhaps annotated as "_[one donation] and a second [donation] recently_" in the enhanced dependencies, but I am not sure if we need any orphan relations in the basic dependencies).

**Comment by amir-zeldes** [comment]
Oh wow, thanks for reporting! Will fix upstream of course. There should be a new GUM release early next year with new data, so I'll push the fixes for these to the UD branch as well once that release comes out.
